# Pipeline: https://dev.azure.com/dnceng/internal/_build?definitionId=1399

trigger:
  batch: true
  branches:
    include:
    - main
    - prerelease
    - release
  paths:
    include:
      - '*'
    exclude:
      - '**.md'
      - eng/Version.Details.xml
      - .github/*
      - docs/*
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT

pr:
  branches:
    include:
    - main
    - prerelease
    - release
  paths:
    include:
      - '*'
    exclude:
      - '**.md'
      - eng/Version.Details.xml
      - .github/*
      - docs/*
      - LICENSE.TXT
      - PATENTS.TXT
      - THIRD-PARTY-NOTICES.TXT

variables:
  - template: /eng/pipelines/common-variables.yml@self
  - template: /eng/common/templates-official/variables/pool-providers.yml@self

  - name: _BuildConfig
    value: Release
  - name: Build.Arcade.ArtifactsPath
    value: $(Build.SourcesDirectory)/artifacts/
  - name: Build.Arcade.LogsPath
    value: $(Build.Arcade.ArtifactsPath)log/$(_BuildConfig)/
  - name: Build.Arcade.TestResultsPath
    value: $(Build.Arcade.ArtifactsPath)TestResults/$(_BuildConfig)/

  # Produce test-signed build for PR and Public builds
  - ${{ if or(eq(variables['_RunAsPublic'], 'true'), eq(variables['Build.Reason'], 'PullRequest')) }}:
    # needed for darc (dependency flow) publishing
    - name: _PublishArgs
      value: ''
    - name: _OfficialBuildIdArgs
      value: ''
    # needed for signing
    - name: _SignType
      value: test
    - name: _SignArgs
      value: ''
    - name: _Sign
      value: false

  # Set up non-PR build from internal project
  - ${{ if and(ne(variables['_RunAsPublic'], 'true'), ne(variables['Build.Reason'], 'PullRequest')) }}:
    # needed for darc (dependency flow) publishing
    - name: _PublishArgs
      value: >-
            /p:DotNetPublishUsingPipelines=true
    - name: _OfficialBuildIdArgs
      value: /p:OfficialBuildId=$(BUILD.BUILDNUMBER)
    # needed for signing
    - name: _SignType
      value: real
    - name: _SignArgs
      value: /p:DotNetSignType=$(_SignType) /p:TeamName=$(_TeamName) /p:Sign=$(_Sign) /p:DotNetPublishUsingPipelines=true
    - name: _Sign
      value: true

  - name: DotNetVersion
    value: '8.0'

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    sdl:
      policheck:
        enabled: true
        exclusionsFile: $(Build.SourcesDirectory)\.config\PoliCheckExclusions.xml
      eslint:
        enabled: false
        justificationForDisabling: 'see https://portal.microsofticm.com/imp/v3/incidents/incident/482258316/summary'
      sourceAnalysisPool:
        name: $(DncEngInternalBuildPool)
        image: windows.vs2022preview.amd64
        os: windows
      tsa:
        enabled: true
    customBuildTags:
    - ES365AIMigrationTooling

    stages:

    # ----------------------------------------------------------------
    # This stage performs build, test, packaging
    # ----------------------------------------------------------------
    - stage: Build
      displayName: Build
      jobs:
      - ${{ if and( notin( variables['Build.Reason'], 'PullRequest' ), eq( variables['Build.SourceBranch'], 'refs/heads/main' ) ) }}:
        - template: /eng/common/templates-official/job/onelocbuild.yml@self
          parameters:
            LclSource: lclFilesfromPackage
            LclPackageId: 'LCL-JUNO-PROD-XCSYNC'
            MirrorRepo: xcsync
            MirrorBranch: main

      - template: /eng/common/templates-official/jobs/jobs.yml@self
        parameters:
          enableMicrobuild: true
          # Publish NuGet packages using v3
          # https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#basic-onboarding-scenario-for-new-repositories-to-the-current-publishing-version-v3
          enablePublishUsingPipelines: true
          enablePublishBuildAssets: true
          enableTelemetry: true
          enableSourceBuild: false
          enableSourceIndex: false
          publishAssetsImmediately: true
          # Publish build logs
          enablePublishBuildArtifacts: true
          # Publish test logs
          enablePublishTestResults: true
          workspace:
            clean: all

          jobs:
          - job: build_macOS
            displayName: Build & Test on macOS
            # timeout accounts for wait times for helix agents up to 30mins
            timeoutInMinutes: 90

            pool:
              name: Azure Pipelines
              vmImage: macOS-latest-internal
              os: macOS

            variables:
              - name: _buildScript
                value: $(Build.SourcesDirectory)/build.sh --ci

            preSteps:
            - checkout: self
              fetchDepth: 1
              clean: true

            steps:                
              - template: /eng/pipelines/templates/buildandtest.yml
                parameters:
                  dotnetScript: $(Build.SourcesDirectory)/dotnet.sh
                  buildScript: $(_buildScript)
                  buildConfig: $(_BuildConfig)
                  repoArtifactsPath: $(Build.Arcade.ArtifactsPath)
                  repoLogPath: $(Build.Arcade.LogsPath)
                  repoTestResultsPath: $(Build.Arcade.TestResultsPath)

          - job: build_Windows
            displayName: Build & Pack & Sign on Windows
            # timeout accounts for wait times for helix agents up to 30mins
            timeoutInMinutes: 90

            pool:
              name: NetCore1ESPool-Internal
              image: windows.vs2022preview.amd64
              os: windows
                          
            variables:
              - name: _buildScript
                value: $(Build.SourcesDirectory)/build.cmd -ci

            preSteps:
            - checkout: self
              fetchDepth: 1
              clean: true

            steps:                
              - template: /eng/pipelines/templates/buildandtest.yml
                parameters:
                  dotnetScript: $(Build.SourcesDirectory)/dotnet.cmd
                  buildScript: $(_buildScript)
                  buildConfig: $(_BuildConfig)
                  repoArtifactsPath: $(Build.Arcade.ArtifactsPath)
                  repoLogPath: $(Build.Arcade.LogsPath)
                  repoTestResultsPath: $(Build.Arcade.TestResultsPath)
                  isWindows: true

    - ${{ if and( notin( variables['Build.Reason'], 'PullRequest' ), eq( variables['Build.SourceBranch'], 'refs/heads/main' ) ) }}:
      - template: /eng/common/templates-official/post-build/post-build.yml@self
        parameters:
          publishingInfraVersion: 3
          enableSymbolValidation: true
          enableSigningValidation: true
          # It's a private repo in github so this won't pass until we create an internal mirror
          enableSourceLinkValidation: false
          validateDependsOn:
          - Build
          publishDependsOn:
          - Validate
          # This is to enable SDL runs part of Post-Build Validation Stage
          SDLValidationParameters:
            enable: true
            params: ' -SourceToolsList @("policheck","credscan")
            -TsaInstanceURL $(_TsaInstanceURL)
            -TsaProjectName $(_TsaProjectName)
            -TsaNotificationEmail $(_TsaNotificationEmail)
            -TsaCodebaseAdmin $(_TsaCodebaseAdmin)
            -TsaBugAreaPath $(_TsaBugAreaPath)
            -TsaIterationPath $(_TsaIterationPath)
            -TsaRepositoryName xcsync
            -TsaCodebaseName xcsync
            -TsaOnboard $True
            -TsaPublish $True
            -PoliCheckAdditionalRunConfigParams @("UserExclusionPath < $(Build.SourcesDirectory)/.config/PoliCheckExclusions.xml")'            
